import seaborn as sns
import matplotlib.pyplot as plt 
df = sns.load_dataset('penguins')
df=df.dropna()
print("First five rows")
print(df.head())
print()
print(df.info())
print()
print(df.describe())
print()
print("Species", df['species'].unique())
print("Island", df['island'].unique())
sns.histplot(data=df, x='body mass', bins=20 , color='steel blue')
plt.title('Histogram of Body Mass')
plt.xlabel('Body Mass (g)')
plt.ylabel('Count')
plt.show()
sns.kdeplot(data=df, x='flipper length', fill=True, hue='species')
plt.title('KDE Plot of Flipper Length by Species')
plt.xlabel('Flipper Length (mm)')
plt.show()
sns.histoplot(data=df,x='flipper length',kde=True,color='coral')
plt.title("Flipper length with curve")
plt.xlabel("Flipper length")
plt.ylabel("count")
plt.show()
sns.scatterplot(data=df,x='flipperlength',y='bodymass',hue="species")
plt.xlabel("Flipper length")
plt.ylabel("Body mass(gms)")
