import pandas as pd
print("-----Part 1: Pandas Series-----")
scores=[98500,87300, 92000, 100000, 87000]
players=pd.Series(scores, index=['SinMonk', 'NotYoMama', 'Sensei_Raccoon', 'Snxz', 'TheRealMVP'])
print(players)
print()
print("-----Part 2: Pandas DataFrame-----")
players_dict={'Player':['SinMonk', 'NotYoMama', 'Sensei_Raccoon', 'Snxz', 'TheRealMVP'],
              'Score':[98500, 87300, 92000, 100000, 87000],
              'Rank':[2, 4, 3, 1, 5]}
df=pd.DataFrame(players_dict)
print(df)
print()
print("-----Part 3: Accessing Rows-----")
print("Row 0(top player):")
print(df.iloc[0])
print()
print("Rows 2 and 3:")
print(df.iloc[2:3])
print()
print("-----Part 4: Reading a csv file-----")
full_df=pd.read_csv('leaderboard.csv')
print("First 5 rows (head):")
print(full_df.head())
print()
print("Last 3 rows (tail):")
print(full_df.tail(3))
print()
print("Dataset information:")
print(full_df.info())
print()
print("-----Part 5: Cleaning the DataFrame-----")
print("Rows with missing values removed(dropna):")
cleaned_df=full_df.dropna()
print(cleaned_df.to_string())
print()
print("Rows with missing values filled with 0(fillna):")
filled_df=full_df.fillna(0)
print(filled_df.to_string())