import turtle
board=turtle.Turtle()
turtle.Screen().bgcolor("Aqua")
board.forward(100)
board.left(120)
board.forward(100)
board.left(120)
board.forward(100)
board.penup()
board.right(150)
board.forward(50)
board.pendown()
board.left(90)
board.forward(100)
board.forward(50)
board.right(120)