import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset('tips')
df= df.dropna()
print(df.head())
print(df.info())
sns.barplot(x='day', y='total_bill',hue="sex", data=df)
plt.title('Total Bill by Day and Gender')
plt.xlabel('Day of the Week')
plt.ylabel('Average Total Bill')
plt.show()
sns.countplot(x='day', data=df,hue='sex')
plt.title('No of dimers per day Day by Gender')
plt.xlabel("Day")
plt.ylabel('Count')
plt.show()
sns.boxplot(x='day', y='total_bill', data=df)
plt.title('Total Bill Distribution by Day')
plt.xlabel('Day')
plt.ylabel('Total Bill')
plt.show()
sns.stripplot(x='day', y='total_bill', data=df, jitter=True)
plt.title('Every bill amount per day (Strip Plot)')
plt.xlabel('Day')
plt.ylabel('Total Bill')
plt.show()
sns.swarmplot(x='day', y='total_bill', data=df)
plt.title('Every bill amount per day (Swarm Plot)')
plt.xlabel('Day')
plt.ylabel('Total Bill')
plt.show()
