import matplotlib.pyplot as plt
days=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
scores=[10, 20, 15, 30, 25, 40, 35]
plt.plot(days, scores,)
plt.show()
plt.plot(days, scores,)
plt.title('Scores Over the Week')
plt.xlabel('Days of the Week')
plt.ylabel('Scores')
plt.grid(True)
plt.ylim(0, 100)
plt.show()  
plt.plot(days, scores,color='blue', marker='o', linestyle='dashed', linewidth=2)
plt.title('Scores Over the Week')
plt.xlabel('Days of the Week')
plt.ylabel('Scores')
plt.grid(True)
plt.ylim(0, 100)
plt.show()
plt.bar(days, scores, color='orange')
plt.title('Scores Over the Week')
plt.xlabel('Days of the Week')
plt.ylim(0, 100)
plt.show()
